export const usersSeed = [
    {
        email : "nz_benhamiche@esi.dz",
        fullName : "BENHAMICHE ZAKARIA",
        role : "ADMIN",
        askingForPromotion: false,
    },
    {
        email : "ny_yasmine@esi.dz",
        fullName : "BAKALEM YASMINE",
        role : "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email : "nj_sid@esi.dz",
        fullName : "JAMYL SID",
        role : "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email : "lf_mourad@esi.dz",
        fullName : "FARAH MOURAD",
        role : "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email: "ah_samir@esi.dz",
        fullName: "HAMMADI SAMIR",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "bt_souad@esi.dz",
        fullName: "TOUATI SOUAD",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "mk_amine@esi.dz",
        fullName: "KACI AMINE",
        role: "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email: "ra_sara@esi.dz",
        fullName: "AMARA SARA",
        role: "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email: "bd_karim@esi.dz",
        fullName: "DJEBBAR KARIM",
        role: "ADMIN",
        askingForPromotion: false,
    },
    {
        email: "sf_nadia@esi.dz",
        fullName: "FERHAT NADIA",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "ab_ilyes@esi.dz",
        fullName: "BOUZID ILYES",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "ms_ines@esi.dz",
        fullName: "SAADI INES",
        role: "TECHNICIAN",
        askingForPromotion: false,
    },
    {
        email: "ht_omar@esi.dz",
        fullName: "TOUATI OMAR",
        role: "TECHNICIAN",
        askingForPromotion: true,
    },
    {
        email: "zr_samir@esi.dz",
        fullName: "RAHMANI SAMIR",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "lm_soumia@esi.dz",
        fullName: "MERABET SOUMIA",
        role: "TECHNICIAN",
        askingForPromotion: true,
    },
    {
        email: "fd_karima@esi.dz",
        fullName: "DJEBBAR KARIMA",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "as_nabil@esi.dz",
        fullName: "SAHRAOUI NABIL",
        role: "TECHNICIAN",
        askingForPromotion: true,
    },
    {
        email: "yt_amina@esi.dz",
        fullName: "TOUATI AMINA",
        role: "STAFF",
        askingForPromotion: false,
    },
    {
        email: "mk_samir@esi.dz",
        fullName: "KACI SAMIR",
        role: "TECHNICIAN",
        askingForPromotion: true,
    },
    {
        email: "ra_karim@esi.dz",
        fullName: "AMARA KARIM",
        role: "STAFF",
        askingForPromotion: false,
    },
    // Users asking to be admin
    {
        email: "admin_candidate1@esi.dz",
        fullName: "BOUZIDI AMINE",
        role: "TECHNICIAN",
        askingForPromotion: true,
        wantsToBeAdmin: true,
    },
    {
        email: "admin_candidate2@esi.dz",
        fullName: "MERABET LINA",
        role: "STAFF",
        askingForPromotion: true,
        wantsToBeAdmin: true,
    },
    {
        email: "admin_candidate3@esi.dz",
        fullName: "KACI YASSINE",
        role: "TECHNICIAN",
        askingForPromotion: true,
        wantsToBeAdmin: true,
    },
]
